# -*- coding: utf-8 -*-
"""desafio_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x8AvL92cflwVkW6tqoM78oZHP_OFRAZx
"""

MENU = '''
[D] ---> Depósito
[S] ---> Saque
[E] ---> Extrato
[X] ---> Sair
'''

saldo = 0
LIMITE_VALOR_SAQUE = 500
extrato = ''
num_saques = 0
LIMITE_SAQUES = 3

while True:
    print('\n########### MENU ###########')
    print(MENU)
    print('############################')
    opcao = input('Escolha sua opção: ').upper()

    if opcao == 'D':
        print('\nDepósito...')
        valor_deposito = float(input('Digite o valor do depósito (R$):'))

        if valor_deposito > 0:
            saldo += valor_deposito
            extrato += f'Depósito de R$ {valor_deposito:.2f}\n'
        else:
            print('Valor de depósito inválido!!!')

    elif opcao == 'S':
        print('\nSaque...')
        valor_saque = float(input('Digite o valor do saque, R$:'))

        excedido_saldo = valor_saque > saldo
        excedido_limite = valor_saque > LIMITE_VALOR_SAQUE
        excedido_saques = num_saques >= LIMITE_SAQUES

        if excedido_saldo:
            print('Saldo insuficiente | Consulte o seu extrato!!!')
        elif excedido_limite:
            print('Excedido o limite do valor do dia!!!')
        elif excedido_saques:
            print('Excedido o limite de saque do dia!!!')

        elif valor_saque > 0:
            saldo -= valor_saque
            extrato += f'Saque: R$ {valor_saque:.2f}'
            num_saques += 1

        else:
            print('Valor inválido | Refaça operação novamente!!!')

    elif opcao == 'E':
        print('=' * 30)
        print('Extrato...')
        print(f'Saldo: R$ {saldo:.2f}')
        print('=' * 30)

    elif opcao == 'X':
        print('\nSaindo...')
        print('Até mais!!! :)')
        break

    else:
        print('Opção Inválida. Por favor escolha uma das opcões do menu!!! ;)')
print('=' * 50)

